---
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    user: root
    ports:
      - '8080'   # Expose uniquement le port 8080 localement
      - '50000:50000' # Port pour les agents Jenkins (JNLP)
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - './jenkins_home:/var/jenkins_home'
    networks:
      - traefik-net

volumes:
  jenkins_home:
    driver: local

networks:
  traefik-net:
    external: true
